version: '3.7'

services:
  app:
    image: sonar-rotas-backend:latest
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: sonar-rotas-backend
    ports:
      - ${PORT_BACKEND}:${PORT_BACKEND}
    restart: always
    env_file: .env