BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[BackOfficeUser] (
    [id] NVARCHAR(1000) NOT NULL,
    [name] NVARCHAR(1000) NOT NULL,
    [email] NVARCHAR(1000) NOT NULL,
    [password] NVARCHAR(1000) NOT NULL,
    [role] NVARCHAR(1000) NOT NULL,
    [createdAt] DATETIMEOFFSET NOT NULL CONSTRAINT [BackOfficeUser_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIMEOFFSET,
    CONSTRAINT [BackOfficeUser_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [BackOfficeUser_id_key] UNIQUE NONCLUSTERED ([id]),
    CONSTRAINT [BackOfficeUser_email_key] UNIQUE NONCLUSTERED ([email])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
