BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Vehicle] ALTER COLUMN [lastSurvey] DATETIMEOFFSET NOT NULL;
ALTER TABLE [dbo].[Vehicle] ALTER COLUMN [expiration] DATETIMEOFFSET NOT NULL;
ALTER TABLE [dbo].[Vehicle] ALTER COLUMN [lastMaintenance] DATETIMEOFFSET NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
